### ISSUE TITLE
Unable to run it globally, need help in setting up the path or environment variables.

### ISSUE THREAD

**Issue by code-grey** [JasonWei512/code-radio-cli#14]
It works in windows, but required me to download the package from github releases, (winget installs but didn't run after, and yes, i started a new shell session.) navigate to the folder where it is saved and also required me to run it like this instead of the "code-radio" command:

> **Suggestion [3,General]: The command code-radio-1.0.3-windows-x86_64-msvc.exe was not found, but does exist in the current 
location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: 
".\code-radio-1.0.3-windows-x86_64-msvc.exe". See "get-help about_Command_Precedence" for more details.**

I think it has to do something with setting up the path or something, but unable to figure it out. Would appreciate some help.

> code-radio : The term 'code-radio' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ code-radio
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (code-radio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JasonWei512** [comment]
This looks like an issue of WinGet and Windows. 
If this is your first time to install a portable excutable with WinGet, you may need to sign out Windows or reboot your computer.

**Comment by JasonWei512** [comment]
Press `Win + R`, run:

```
%LOCALAPPDATA%\Microsoft\WinGet\Links
```

Can you see `code-radio.exe` in the folder?

**Comment by fratellomio** [comment]
> 

Hi, I run into the same problem. In my case, there's no code-radio.exe in the folder.

**Comment by DoraTiger** [comment]
> Press `Win + R`, run:
> 
> ```
> %LOCALAPPDATA%\Microsoft\WinGet\Links
> ```
> 
> Can you see `code-radio.exe` in the folder?

Hi, I got same problem, I installed code-radio though command `winget install code-radio-cli`, it tell me to restart the powershell, after restart I got these
```
+ code-radio -v 5
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (code-radio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
I can find the file `code-radio.exe` which size is 0kb in `%LOCALAPPDATA%\Microsoft\WinGet\Links`

**Comment by code-grey** [comment]
> Press `Win + R`, run:
> 
> ```
> %LOCALAPPDATA%\Microsoft\WinGet\Links
> ```
> 
> Can you see `code-radio.exe` in the folder?

Surprisingly that folder is empty.
However, in the packages folder, it's available, but still not as `code-radio.exe`.
`C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\JasonWei512.code-radio-cli_Microsoft.Winget.Source_8wekyb3d8bbwe\code-radio-1.0.3-windows-x86_64-msvc`

(View hidden items is enabled, just in case)

**Comment by fratellomio** [comment]
I just updated to the latest version (1.0.5), and then I updated my powershell alias from the previous version, which is  

``` set-alias code-radio code-radio-1.0.4-windows-x86_64-msvc.exe ``` to ```set-alias code-radio code-radio-1.0.5-windows-x86_64-msvc.exe```  
but I noticed that the file name right now is code-radio so I changed it again to ``` set-alias code-radio code-radio.exe``` and it still didn't work.
I tried to remove the alias and just input the original command ```code-radio``` into powershell and got this error message instead: 

![image](https://github.com/JasonWei512/code-radio-cli/assets/6015405/61ab0c86-bb67-4340-b045-f45cd528d586)
