### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by excellentsport** [JasonWei512/code-radio-cli#20]
I haven't fired up Code Radio CLI in awhile, but today I'm getting a 404 error when trying to launch the program via MINGW64 and Powershell. I tried downloading a new copy of the 1.03 release, and I'm still having the same 404 error. I can access code radio via the browser, if that is useful information.

I tried using the "-s" flag as well and got this error: "Error: error decoding response body: invalid type: integer `404`, expected struct CodeRadioMessage at line 1 column 3"

**Comment by JasonWei512** [comment]
Looks like Code Radio no longer uses the old WebSocket API.
This will be fixed in https://github.com/JasonWei512/code-radio-cli/pull/21 .
You can get CI builds from https://github.com/JasonWei512/code-radio-cli/actions .

**Comment by JasonWei512** [comment]
It's fixed in [v1.0.4](https://github.com/JasonWei512/code-radio-cli/releases/tag/v1.0.4) .
