### ISSUE TITLE
Error: Server-Sent Events Error: HttpStream

### ISSUE THREAD

**Issue by Borber** [JasonWei512/code-radio-cli#23]
![image](https://github.com/JasonWei512/code-radio-cli/assets/30563826/f18511a3-1ea8-4a5c-ad5b-4c7c3c770062)

I don't know why, but the web can be accessed normally

**Comment by JasonWei512** [comment]
Fixed in [v1.0.5](https://github.com/JasonWei512/code-radio-cli/releases/tag/v1.0.5) .

**Comment by Borber** [comment]
> Fixed in [v1.0.5](https://github.com/JasonWei512/code-radio-cli/releases/tag/v1.0.5) .

Confirmed the fix, great🥰
